name: Compilar Tasmota Sensors ESP8266

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar PlatformIO y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install "SCons==4.7.0"
          pip install platformio

      - name: Crear dummy FortranCommon si es necesario
        run: |
          python3 -c "import sys, glob, os; [open(os.path.join(d, 'FortranCommon.py'), 'a').close() for p in sys.path for d in glob.glob(os.path.join(p, 'SCons', 'Tool'))]" || true

      - name: Compilar firmware tasmota-sensors
        run: |
          platformio run -e tasmota-sensors

      - name: Subir binario como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasmota-sensors-9600
          path: |
            .pio/build/tasmota-sensors/firmware.bin*
            .pio/build/tasmota-sensors/firmware.bin
