name: Compilar Tasmota Sensors ESP8266

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar PlatformIO 6.1.19
        run: |
          python -m pip install --upgrade pip
          pip install "platformio==6.1.19"

      - name: Compilar firmware tasmota-sensors
        run: |
          platformio run -e tasmota-sensors

      - name: Subir binario como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasmota-sensors-9600
          path: |
            .pio/build/tasmota-sensors/firmware.bin*
            .pio/build/tasmota-sensors/firmware.bin
